//go:build darwin && cgo

package main

import "embed"

//go:embed trayicons/mono.png
var darwinTrayMonoPNG []byte

// State-aware menu bar glyphs (<style>-<idle|proxy|tun>.png, 44 px = 22 pt @2x)
// generated by scripts/generate-tray-icons.mjs. mono.png above is what the
// status item is created with; the poller swaps in the matching state asset.
//
//go:embed trayicons/state/*.png
var darwinTrayStatePNGs embed.FS
