// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from '../models'
import { options } from '../models'

export function ActivateProfile(arg1: string): Promise<main.AppState>

export function ApplyUpdate(): Promise<void>

export function CheckForUpdates(): Promise<main.UpdateState>

export function Connect(): Promise<main.AppState>

export function DeleteProfile(arg1: string): Promise<main.AppState>

export function Disconnect(): Promise<main.AppState>

export function EnsureTunReady(): Promise<main.TunSetupResult>

export function FetchRulesOverview(): Promise<main.RulesOverview>

export function GetAppState(): Promise<main.AppState>

export function GetDesktopPrefs(): Promise<main.DesktopPrefs>

export function GetLaunchOnStartupPreference(): Promise<boolean>

export function GetPreferredLanguage(): Promise<string>

export function GetProfilePaths(arg1: string): Promise<main.ProfilePaths>

export function GetProfileProxyGroupsBaseline(
  arg1: string,
): Promise<main.ProfileProxyGroupsBaseline>

export function GetProfileRulesBaseline(
  arg1: string,
): Promise<main.ProfileRulesBaseline>

export function GetTrayAvailability(): Promise<boolean>

export function GetTunStatus(): Promise<main.ServiceState>

export function GetUpdateState(): Promise<main.UpdateState>

export function ImportProfileFromURL(
  arg1: string,
  arg2: string,
): Promise<main.AppState>

export function InstallService(): Promise<main.TunSetupResult>

export function ListProfiles(): Promise<Array<main.Profile>>

export function MarkQuitIntent(): Promise<void>

export function OnSecondInstance(
  arg1: options.SecondInstanceData,
): Promise<void>

export function PeekSubscriptionFromURL(
  arg1: string,
): Promise<main.SubscriptionPeek>

export function ReadProfileConfig(arg1: string): Promise<main.ProfileConfigPeek>

export function ReadServiceLatestLog(arg1: number): Promise<main.ServiceLogPeek>

export function RefreshHomeInsight(): Promise<main.AppState>

export function RefreshProfileSubscription(arg1: string): Promise<main.AppState>

export function RefreshProxies(): Promise<main.AppState>

export function RenameProfile(
  arg1: string,
  arg2: string,
): Promise<main.AppState>

export function SelectProxyGroup(arg1: string): Promise<main.AppState>

export function SetCloseToTrayPreference(arg1: boolean): Promise<main.AppState>

export function SetLaunchOnStartupPreference(arg1: boolean): Promise<void>

export function SetMode(arg1: string): Promise<main.AppState>

export function SetProfileAutoUpdate(
  arg1: string,
  arg2: boolean,
  arg3: number,
): Promise<main.AppState>

export function SetProfileMergeTemplate(
  arg1: string,
  arg2: string,
): Promise<main.AppState>

export function SetProfileProxyTemplate(
  arg1: string,
  arg2: string,
): Promise<main.AppState>

export function SetProfileRulesTemplate(
  arg1: string,
  arg2: string,
): Promise<main.AppState>

export function SetProxyNode(arg1: string, arg2: string): Promise<main.AppState>

export function SetTrafficMode(arg1: string): Promise<main.AppState>

export function SetTrafficSettings(
  arg1: main.TrafficSettings,
): Promise<main.DesktopPrefs>

export function SetTunSettings(
  arg1: main.TunSettings,
): Promise<main.DesktopPrefs>

export function SetUpdateChannel(arg1: string): Promise<main.UpdateState>

export function StartedMinimized(): Promise<boolean>

export function UpdateProfileInfo(
  arg1: string,
  arg2: string,
  arg3: string,
): Promise<main.AppState>

export function WriteProfileConfig(
  arg1: string,
  arg2: string,
): Promise<main.AppState>
