// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProfile(arg1) {
  return window['go']['main']['App']['ActivateProfile'](arg1)
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']()
}

export function AutoSelectProxyGroup() {
  return window['go']['main']['App']['AutoSelectProxyGroup']()
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']()
}

export function Connect() {
  return window['go']['main']['App']['Connect']()
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1)
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']()
}

export function EnsureTunReady() {
  return window['go']['main']['App']['EnsureTunReady']()
}

export function FetchRulesOverview() {
  return window['go']['main']['App']['FetchRulesOverview']()
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']()
}

export function GetProfilePaths(arg1) {
  return window['go']['main']['App']['GetProfilePaths'](arg1)
}

export function GetTunStatus() {
  return window['go']['main']['App']['GetTunStatus']()
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']()
}

export function ImportProfileFromURL(arg1, arg2) {
  return window['go']['main']['App']['ImportProfileFromURL'](arg1, arg2)
}

export function InstallService() {
  return window['go']['main']['App']['InstallService']()
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']()
}

export function OnSecondInstance(arg1) {
  return window['go']['main']['App']['OnSecondInstance'](arg1)
}

export function PeekSubscriptionFromURL(arg1) {
  return window['go']['main']['App']['PeekSubscriptionFromURL'](arg1)
}

export function ReadProfileConfig(arg1) {
  return window['go']['main']['App']['ReadProfileConfig'](arg1)
}

export function ReadServiceLatestLog(arg1) {
  return window['go']['main']['App']['ReadServiceLatestLog'](arg1)
}

export function RefreshHomeInsight() {
  return window['go']['main']['App']['RefreshHomeInsight']()
}

export function RefreshProfileSubscription(arg1) {
  return window['go']['main']['App']['RefreshProfileSubscription'](arg1)
}

export function RefreshProxies() {
  return window['go']['main']['App']['RefreshProxies']()
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2)
}

export function SelectProxyGroup(arg1) {
  return window['go']['main']['App']['SelectProxyGroup'](arg1)
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1)
}

export function SetProfileAutoUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProfileAutoUpdate'](arg1, arg2, arg3)
}

export function SetProfileMergeTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetProfileMergeTemplate'](arg1, arg2)
}

export function SetProfileProxyTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetProfileProxyTemplate'](arg1, arg2)
}

export function SetProfileRulesTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetProfileRulesTemplate'](arg1, arg2)
}

export function SetProxyNode(arg1, arg2) {
  return window['go']['main']['App']['SetProxyNode'](arg1, arg2)
}

export function SetTrafficMode(arg1) {
  return window['go']['main']['App']['SetTrafficMode'](arg1)
}

export function SetUpdateChannel(arg1) {
  return window['go']['main']['App']['SetUpdateChannel'](arg1)
}

export function UpdateProfileInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfileInfo'](arg1, arg2, arg3)
}

export function WriteProfileConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteProfileConfig'](arg1, arg2)
}
